### ISSUE TITLE
Ideas for Procgen Maps

### ISSUE THREAD

**Issue by ShockMicro** [gegy1000/bed-wars#17]
- [ ] Multiple biomes, one for each team and then one for the middle.
- [ ] Villagers could be randomized into different mobs? Could be different for every biome.
- [ ] Different variants of items that show up in different biomes. Examples include: Bridge snowballs instead of eggs, they build with ice; Fire Charge bridges that fly straight but place magma blocks instead of wool, replacing both the Bridge Egg _and_ the Fireball.
- [ ] Team Islands are actual islands instead of platforms (except maybe for a platform theme?)

**Comment by gegy1000** [comment]
I really like the idea of the "theming" of the map changing the items/blocks you use!

**Comment by ShockMicro** [comment]
Yeah, there could even be Procgen-exclusive blocks like ice or magma blocks that are completely new and not replacing something per-biome. Maybe completely new items would be determined by the center area's biome. If the center is a Magma biome, every team gets magma blocks even if they're a Tundra.

**Comment by ShockMicro** [comment]
One more comment on the matter (I'll edit this onto the original with a checkbox), actual team islands instead of just platforms, this would help the player distinguish which biome they're in better.

**Comment by ShockMicro** [comment]
A biome that uses the old platform and gives you some industrial-themed things might be cool, like iron golems instead of Bridge Eggs or something.

**Comment by ShockMicro** [comment]
This issue has moved over to the BedWars/AnchorWars Design Doc. 
Check it here: https://docs.google.com/document/d/1-r-O_gii4k619tr6PU7fr39pMDWiV7KZwMP4k62boqc/edit#
